name: flutter_inappwebview_ios
description: iOS implementation of the flutter_inappwebview plugin.
version: 1.2.0-beta.2
homepage: https://inappwebview.dev/
publish_to: none
repository: https://github.com/pichillilorenzo/flutter_inappwebview/tree/master/flutter_inappwebview_ios

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview_platform_interface:
    path: ../flutter_inappwebview_platform_interface
  flutter_inappwebview_internal_annotations:
    path: ../dev_packages/flutter_inappwebview_internal_annotations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    implements: flutter_inappwebview
    platforms:
      ios:
        pluginClass: InAppWebViewFlutterPlugin
        dartPluginClass: IOSInAppWebViewPlatform
