name: flutter_inappwebview
description: A Flutter plugin that allows you to add an inline webview, to use a headless webview, and to open an in-app browser window.
version: 6.2.0-beta.2
homepage: https://inappwebview.dev/
repository: https://github.com/FrostyBen/flutter_inappwebview

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview_platform_interface:
    path: packages/flutter_inappwebview_platform_interface
  flutter_inappwebview_android:
    path: packages/flutter_inappwebview_android
  flutter_inappwebview_ios:
    path: packages/flutter_inappwebview_ios

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.12
  generators:
    path: packages/dev_packages/generators

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_inappwebview_android
      ios:
        default_package: flutter_inappwebview_ios
      macos:
        default_package: flutter_inappwebview_macos
      web:
        default_package: flutter_inappwebview_web
      windows:
        default_package: flutter_inappwebview_windows

  assets:
    - packages/flutter_inappwebview/assets/t_rex_runner/t-rex.html
    - packages/flutter_inappwebview/assets/t_rex_runner/t-rex.css
