name: flutter_inappwebview_platform_interface
description: Platform interface for flutter_inappwebview plugin.
version: 1.0.0
publish_to: none
homepage: https://inappwebview.dev/
repository: https://github.com/pichillilorenzo/flutter_inappwebview_platform_interface

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  flutter_inappwebview_internal_annotations:
    path: ../dev_packages/flutter_inappwebview_internal_annotations

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.12
  generators:
    path: ../dev_packages/generators

flutter:
  plugin:
    implements: flutter_inappwebview
    platforms:
      android:
        default_package: flutter_inappwebview_platform_interface
      ios:
        default_package: flutter_inappwebview_platform_interface
      macos:
        default_package: flutter_inappwebview_platform_interface
      web:
        default_package: flutter_inappwebview_platform_interface
      windows:
        default_package: flutter_inappwebview_platform_interface
      linux:
        default_package: flutter_inappwebview_platform_interface
